language: java
dist: bionic
jdk: openjdk11

cache:
  directories:
    - "$HOME/.m2"

install:
  - cp -f .travis/settings.xml $HOME/.m2 # configure maven security

script:
  - mvn -P prod clean verify -B # build and test with prod profile

deploy:
  - provider: script
    script: mvn -P nexus deploy -B -DskipTests=true
    on:
      branch: develop
  - provider: script
    script: mvn -P nexus deploy -B -DskipTests=true
    on:
      tags: true
      branch: master